FROM node:20.19.2-bullseye
# See: https://docs.expo.dev/build-reference/infrastructure/

WORKDIR /app

ARG LOCAL_IP="0.0.0.0"

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS="0.0.0.0"
ENV REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP}

COPY package*.json .
COPY .npmrc .

RUN npm install

COPY . .

EXPOSE 8081

ENTRYPOINT [ "bash", "./docker-dev.sh" ]

CMD npm run web