FROM node:21.2.0-bullseye

WORKDIR /app

ARG LOCAL_IP="0.0.0.0"

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS="0.0.0.0"
ENV REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP}

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 8082

ENTRYPOINT [ "bash", "./docker-dev.sh" ]

CMD npm run storybook