FROM node:21.2.0-bullseye

WORKDIR /app

# RUN apk add --no-cache bash

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS="0.0.0.0"
ENV REACT_NATIVE_PACKAGER_HOSTNAME="0.0.0.0"

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 8081

ENTRYPOINT [ "bash", "./docker-dev.sh" ]

CMD npm run web